# -*- coding: utf-8 -*-
"""Zomato_Mumbai_Data_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bhKJ3664dO1znjOGyHkJ7UI5AkCXrmd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.io as pio

"""**Importing the libraries**"""

pio.renderers.default = 'svg'

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Colab Notebooks

dataset=pd.read_csv("Zomato_Mumbai_Dataset.csv", delimiter='|')

"""**Importing the dataset**

"""

dataset.head()

"""**Getting Basic Information about the Dataset**

"""

dataset.shape

dataset.info()

dataset.describe()

"""**Cleaning the Dataset**

**(a) Removing the redundunt rows of data**
"""

wrong_data = dataset ['PAGE NO'] == 'PAGE NO'
dataset [wrong_data]

"""## Performing Negation of the wrong dataset and then storing the correct data back in the raw_df DataFrame ## **This permamnently remove the wrong data from the original dataframe**



"""

dataset = dataset [~wrong_data]

"""# Dropping columns which are not required for further analysis"""

dataset.drop(['URL', 'PAGE NO', 'CITY'], axis = 1, inplace=True)

dataset.head()

"""**(b) Removing the Null Records**

# Checking for Null records


"""

dataset.isnull().sum()

"""# Checking for a null row"""

dataset [dataset ['PRICE'].isnull()]

"""# Droping the above row from the dataset"""

dataset = dataset.drop(labels=15080, axis=0)

"""# Replacing the other null records with NA"""

dataset.fillna('NA', inplace=True)

"""# Confirming all the null records are correct

"""

dataset.isnull().sum()

"""**(c) Converting the DataTypes of numerical columns to numeric dataype**

**Checking for text values in the column before converting it to numeric datatype**

It counts how many times each rating appears in the dataset.

In simple words:

“How many restaurants have rating 4.0?”
“How many have rating 3.5?”
“How many have rating 5.0?”

Simple Summary
Value	Meaning

**NEW	- Newly added restaurant, no rating yet
**Opening - Not opened yet
** -	= No rating available

All three are not actual ratings.
"""

dataset['RATING'].value_counts()

"""# Replacing the text values with '0'

"""

dataset ['RATING'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

"""# Checking for text values in the column before converting it to numeric datatype

"""

dataset ['VOTES'].value_counts()

"""# Replacing the text values with '0'"""

dataset['VOTES'].replace(to_replace=['-','NEW','Opening'], value='0', inplace=True)

"""# Changing Data Type of the numerical columns

"""

dataset['PRICE'] = dataset['PRICE'].astype('int64')
dataset['RATING'] = dataset['RATING'].astype('float64')
dataset['VOTES'] = dataset['VOTES'].astype('int64')

"""**complete structural information about your dataset.**

Your dataset has 14,138 rows (records)

Even though index shows 0 to 15079,
only 14,138 rows are active (after cleaning).

This means:
You previously removed some rows
"""

dataset.info()

"""**(d) Working with 'Timing' column**"""

dataset['TIMING'].value_counts()

"""# Splitting the column and storing it in temp_df dataframe"""

temp_df = dataset['TIMING'].str.split("(", n=1, expand=True)
temp_df

"""# Assigning the columns back to the raw_df dataframe

"""

dataset ['TIMING'] = temp_df[0]
dataset ['DAYS_OPEN'] = temp_df[1]
dataset.head()

"""# Removing the bracket character from Days column"""

dataset['DAYS_OPEN'] = dataset['DAYS_OPEN'].str.replace('\)','',regex=True)
dataset.head()

"""# Checking for Null records in DAYS_OPEN column

"""

dataset.isnull().sum()

"""# Replacing the Null values with 'NA'

"""

dataset.fillna('NA', inplace=True)

"""# Checking info of all the columns

"""

dataset.info()

"""**(e) Removing the restaurant records whose Rating or Votes is 0**

# Finding those restaurant whose has 0 Rating or Votes


"""

useless_data = (dataset['RATING'] == 0.0) | (dataset['VOTES'] == 0)
dataset[useless_data]

"""## Performing Negation of the useless dataset and then storing the correct data back in the raw_df DataFrame ## This permamnently remove the wrong data from the original dataframe

"""

dataset = dataset[~useless_data]

"""**(f) Working on 'RATING_TYPE' Column**

# Checking the unique values in the column


"""

dataset['RATING_TYPE'].value_counts()

"""# Translating the texts into proper English text



"""

dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace='Excelente' , value='Excellent')
dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace=['Veľmi dobré','Bardzo dobrze','Muy Bueno','Velmi dobré'] , value='Very Good')
dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace=['Skvělá volba','Dobrze','Bueno','Buono','Dobré','Bom','Skvělé'] , value='Good')
dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace=['Priemer','Média','Çok iyi'] , value='Average')
dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace=['Průměr','Promedio','Ortalama','Muito Bom','İyi'] , value='Poor')
dataset['RATING_TYPE'] = dataset['RATING_TYPE'].replace(to_replace=['Baik','Biasa','Media','Sangat Baik'] , value='Very Poor')

"""# Checking all the values correctly mapped


"""

dataset['RATING_TYPE'].value_counts()

"""**(g) Working on 'REGION' Column**

"""

dataset['REGION'].value_counts()

"""# Removing the irrelevant text from the Region column

"""

dataset ['REGION'] = dataset['REGION'].str.replace('[a-zA-Z].+-- ','',regex=True)

"""# Removing the West & East from the Region column

"""

dataset['REGION'] = dataset['REGION'].str.replace(' West| west| East| east','',regex=True)

dataset['REGION'].value_counts()

""" # Replacing smart

"""

dataset['REGION'] = dataset['REGION'].str.replace('4 Bungalows 7 Andheri | Azad Nagar | Near Andheri Station Veera Desai Area', 'Andheri', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Bandra Kurla Complex', 'Bandra', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('CBD-Belapur', 'CBD Belapur', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Girgaon Chowpatty', 'Chowpatty', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Dadar Shivaji Park', 'Dadar', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Flea Bazaar Café Kamala Mills Compound', 'Lower Parel', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Runwal Green', 'Mulund', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Mumbai CST Area', 'Mumbai Central', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Kopar Khairane | Seawoods | Turbhe|Ulwe', 'Navi Mumbai', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('New Panvel Old Panvel', 'Panvel', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Kamothe', 'Sion', regex=True)
dataset['REGION'] = dataset['REGION'].str.replace('Ghodbunder Road Majiwada', 'Thane', regex=True)

"""**h. Removing Duplicate records**
# Finding all the duplicate rows
"""

dataset[dataset.duplicated()]

"""# Dropping all the duplicate rows



"""

dataset = dataset.drop_duplicates()

"""**Copying the cleaned data into a new DataFrame**"""

zomato_df = dataset.copy()

zomato_df.head()

"""**Performing Exploratory Data Analysis**/

 #How many restaurants are in Mumbai for each type of cuisine?**

"""

!pip install -U kaleido

import plotly.io as pio
pio.renderers.default = 'svg'

import plotly.io as pio
pio.renderers.default = "colab"
fig.show()

!pip install -U kaleido

import plotly.io as pio
pio.renderers.default = "colab"

fig.show()

"""**Q2) What are the percentage of restaurants by Rating Type in Mumbai?**

"""

rating_type_df['COUNT OF RESTAURANTS'] = pd.to_numeric(
    rating_type_df['COUNT OF RESTAURANTS'],
    errors='coerce'
)

rating_type_df['PERCENTAGE'] = (
    rating_type_df['COUNT OF RESTAURANTS'] /
    rating_type_df['COUNT OF RESTAURANTS'].sum()
) * 100

rating_type_df['PERCENTAGE'] = rating_type_df['PERCENTAGE'].round(2)

rating_type_df

fig = px.pie(
    rating_type_df,
    names='RATING_TYPE',  # correct name
    values='COUNT OF RESTAURANTS',
    color='RATING_TYPE',
    title='Percentage of Restaurants by Rating Type'
)

fig.update_traces(
    textposition='inside',
    textinfo='percent+label'
)

fig.show()

"""**Q3) Which are the Top 10 highest rated Seafood Restaurant in Mumbai?**

"""

seafood_df = zomato_df[
    zomato_df['CUSINE_CATEGORY'].str.contains('Seafood', case=False, na=False)
]

top_seafood = seafood_df.sort_values(
    by='RATING',
    ascending=False
).head(10)

top_seafood

"""**Q4) Which is the best Food Truck in Mumbai?**

✅ What It Means (Very Simple)

1️⃣ First line
👉 It selects only restaurants where cuisine type is Food Truck.
Now foodtruck_df contains only food trucks.

2️⃣ Second line
👉 It sorts those food trucks by rating (highest first).
👉 Then shows only the top 2 restaurants.

🎯 In One Sentence

Your code finds:

⭐ The top 2 highest-rated Food Truck restaurants.

"""

foodtruck_df = zomato_df[zomato_df['CUSINE TYPE'] == 'Food Truck']
foodtruck_df.sort_values(by='RATING',ascending=False).head(2)

"""**Q5) Which places have the highest rated restaurant for each Cuisine Type in Mumbai?**

# Assuming restaurants having rating above 4.5
"""

highest_rated_df = zomato_df[zomato_df['RATING'] >= 4.5]
highest_rated_df

"""**No. of Best Restaurant for each Cuisine Type by Places**"""

import plotly.express as px

fig = px.histogram(
    highest_rated_df,
    x='REGION',
    color='CUSINE TYPE',
    title='No. of Best Restaurants for Each Cuisine Type by Places'
)

fig.update_xaxes(categoryorder="total descending")

fig.show()

"""**Q6) What is the Avg Price Distibution of highest rated restaurant for each Cuisine Type in Mumbai?**

"""

highest_rated_price_df = (
    highest_rated_df
        .groupby(['REGION', 'CUSINE TYPE'])['PRICE']
        .mean()
        .reset_index()
)

highest_rated_price_df.head()

"""**Avg Price Distibution of High rated restaurant for each Cuisine Type**

"""

fig = px.scatter(highest_rated_price_df, x="REGION", y="PRICE", color="CUSINE TYPE", symbol="CUSINE TYPE",
title=' Avg Price Distibution of High rated restaurant for each Cuisine Type').update_traces(marker_size=10)

fig.show()

"""**Q7) Which areas have a large number of Chinese Restaurant Market?**

"""

chinese_df = zomato_df[
    zomato_df['CUSINE_CATEGORY'].str.contains('Chinese', case=False, na=False)
]

chinese_df

"""What This Code Does (Simple)

1️⃣ Groups Chinese restaurants by Region
2️⃣ Counts number of restaurants (NAME → count)
3️⃣ Calculates average price (PRICE → mean)
4️⃣ Renames columns properly
5️⃣ Sorts by highest number of restaurants
6️⃣ Shows top 25 regions
"""

chinese_rest_df = (
    chinese_df
        .groupby('REGION')
        .agg({
            'NAME': 'count',
            'PRICE': 'mean'
        })
        .rename(columns={
            'NAME': 'COUNT OF RESTAURANTS',
            'PRICE': 'AVERAGE PRICE'
        })
        .reset_index()
)

chinese_rest_df = chinese_rest_df.sort_values(
    by='COUNT OF RESTAURANTS',
    ascending=False
).head(25)

chinese_rest_df.head()

"""**No. of Chinese Restaurant by Places**

"""

import plotly.express as px

fig = px.bar(
    chinese_rest_df,
    x='REGION',
    y='COUNT OF RESTAURANTS',
    color='AVERAGE PRICE',
    title='Number of Chinese Restaurants by Region',
    labels={
        'REGION': 'Region',
        'COUNT OF RESTAURANTS': 'Number of Restaurants',
        'AVERAGE PRICE': 'Average Price'
    }
)

fig.update_layout(title_x=0.5)

fig.show()

"""**Q8) Is there a relation between Price and Rating by each Cuisine Type?**

"""

price_rating_df = zomato_df.groupby(['CUSINE TYPE', 'RATING'])['PRICE'].mean().reset_index()
price_rating_df

fig = px.line(price_rating_df, y="PRICE", x="RATING",color='CUSINE TYPE')

fig.show()

"""**Q9) Is there a relation between Region and Price?**

"""

region_price_df = zomato_df.groupby(['REGION'])['PRICE'].mean().reset_index()
region_price_df

fig = px.scatter(region_price_df, x="REGION", y="PRICE").update_traces(marker_size=8)
fig.show()

fig = px.scatter(
    region_price_df,
    x="PRICE",
    y="REGION"
)
fig.show()

"""**Q10) Find the list of Affordable Restaurants?**
#The criteria for Affordable Restaurants would be:-
1) Low Price
2) High Rated

First step will be to find the restaurants with average cost 1/4th the average cost of most expensive restaurant in our dataframe.

Let me explain:-The most expensive restaurant has an average meal cost= 6000. We'll try to stay economical and only pick
the restaurants that are 1/4th of 6000.

"""

max_price = zomato_df['PRICE'].max()
one_fourth_price = max_price/4
one_fourth_price

"""# Finding list of restaurants that have price less than and equal to 1/4th of the max price i.e Finding Cheap Restauran"""

# Select required columns
aff_rest_df = zomato_df[
    ['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE']
]

# Filter restaurants with price <= 1250
aff_rest_df = aff_rest_df[aff_rest_df['PRICE'] <= 1250]

# Sort by price (lowest first)
aff_rest_df.sort_values(by='PRICE', inplace=True)

aff_rest_df

"""# Finding the highest rated list of restaurants"""

highrate_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE','RATING']]
highrate_rest_df = highrate_rest_df[highrate_rest_df['RATING'] >= 4.5]
highrate_rest_df.sort_values(by='PRICE', inplace=True)
highrate_rest_df

"""**Now, we'll merge the aff_rest_df with highrate_rest_df to obtain the intersection i.e the list of Affordable Restaurants !**

# Affordable Restaurants with low price and high rating

"""

# Merge affordable restaurants with high-rated restaurants
highrate_aff_df = pd.merge(
    aff_rest_df,
    highrate_rest_df,
    how='inner',
    on=['NAME', 'REGION']
)

# Select required columns
highrate_aff_df = highrate_aff_df[
    ['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']
]

# Rename columns properly
highrate_aff_df.rename(
    columns={
        'PRICE_x': 'PRICE',
        'CUSINE_CATEGORY_x': 'CUSINE_CATEGORY',
        'CUSINE TYPE_x': 'CUSINE TYPE'
    },
    inplace=True
)

highrate_aff_df

"""**Q10) Find the list of most Reliable Restaurants?**

The criteria for most Reliable Restaurants would be:-
1) Low Price
2) High Rated
3) Large No. of Votes

First step will be to find the restaurants with Votes greater than Mean of Votes


"""

mean_votes = zomato_df['VOTES'].mean()
mean_votes

"""# Finding list of restaurants that have Votes greater than and equal to Mean of Vote"""

mean_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'VOTES']]
mean_rest_df = mean_rest_df[mean_rest_df['VOTES'] > 177]
mean_rest_df.sort_values(by='VOTES', inplace=True)
mean_rest_df

mean_rest_df = zomato_df[['NAME', 'PRICE', 'CUSINE_CATEGORY', 'REGION', 'CUSINE TYPE', 'VOTES']]
mean_rest_df = mean_rest_df[mean_rest_df['VOTES'] > 177]
mean_rest_df.sort_values(by='VOTES', inplace=True)
mean_rest_df
fig.show()

"""**The dataframe below represents restaurants that are both highly rated and affordable.**

These restaurants were identified by intersecting highrate_aff_df and mean_rest_df.

**The selected restaurants satisfy the following conditions:**

Cost is below ₹1250

High customer ratings

Strong vote count (above average)
"""

# Merge reliable (above-average votes) and high-rated affordable restaurants
reliable_rest_df = pd.merge(
    mean_rest_df,
    highrate_aff_df,
    how='inner',
    on=['NAME', 'REGION']
)

# Select required columns
reliable_rest_df = reliable_rest_df[
    ['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']
]

# Rename columns (remove _x suffix)
reliable_rest_df.rename(
    columns={
        'PRICE_x': 'PRICE',
        'CUSINE_CATEGORY_x': 'CUSINE_CATEGORY',
        'CUSINE TYPE_x': 'CUSINE TYPE'
    },
    inplace=True
)

reliable_rest_df

# Merge reliable (above-average votes) and high-rated affordable restaurants
reliable_rest_df = pd.merge(
    mean_rest_df,
    highrate_aff_df,
    how='inner',
    on=['NAME', 'REGION']
)

# Select required columns
reliable_rest_df = reliable_rest_df[
    ['NAME', 'PRICE_x', 'CUSINE_CATEGORY_x', 'REGION', 'CUSINE TYPE_x']
]

# Rename columns (remove _x suffix)
reliable_rest_df.rename(
    columns={
        'PRICE_x': 'PRICE',
        'CUSINE_CATEGORY_x': 'CUSINE_CATEGORY',
        'CUSINE TYPE_x': 'CUSINE TYPE'
    },
    inplace=True
)

reliable_rest_df
fig.show()